baseURL = "https://www.whistlersrun.com"
languageCode = "en-us"
title = "Whistler's Run & Rescue"
enableRobotsTXT = true
disableAliases = true
# post pagination
paginate = "10"
summaryLength = 20
googleAnalytics = " " # Your ID# search 

#################### default parameters ################################

[params]
  # Google Analitycs
  googleAnalytics = " " # Your ID# search 
  minifyBundles = true

# add redirects/headers
  [outputs]
  home = ["HTML", "RSS", "REDIRECTS", "HEADERS"]

# remove .{ext} from text/netlify
[mediaTypes."text/netlify"]
  suffixes = [""]
  delimiter = ""

# add output format for netlify _redirects
[outputFormats.REDIRECTS]
  mediatype = "text/netlify"
  baseName = "_redirects"
  isPlainText = true
  notAlternative = true

# add output format for netlify _headers
[outputFormats.HEADERS]
  mediatype = "text/netlify"
  baseName = "_headers"
  isPlainText = true
  notAlternative = true

[sitemap]
  changefreq = "monthly"
  filename = "sitemap.xml"
  priority = 0.5

[markup.goldmark.renderer]
  unsafe= true