const autoprefixer = require('autoprefixer')
const purgecss = require('@fullhuman/postcss-purgecss')

module.exports = {
  plugins: [
    autoprefixer(),
    purgecss({
      content: [
        './layouts/**/*.html',
        './layouts/**/*.svg',
        './content/**/*.md',
      ],
      safelist: [
        'is-active',
        'nav-open',
        'swiper-pagination-bullet',
        'swiper-pagination-bullet-active',
        'video-paused',
        'video-playing',
        'expand',
        'collapse',
        'home',
        'bg-gray',
        'footprints--left',
        'footprints--right',
        'home-hero',
        'page-home',
        'parent-page-home',
        'page-about-us',
        'parent-page-about-us',
        'page-sustainability',
        'parent-page-sustainability',
        'page-careers',
        'parent-page-careers',
        'page-milksource-genetics',
        'parent-page-milksource-genetics',
        'page-contact',
        'parent-page-contact',
        'page-news',
        'parent-page-news',
        'page-media',
        'parent-page-media',
        'page-tours',
        'parent-page-tours',
        'grid-1',
        'grid-2',
        'grid-3',
        'grid-4',
        'grid-5',
        'grid-6',
        'animal-lovers',
        'crt-widget',
        'crt-logo',
        'crt-widget-branded',
        'crt-image',
        'crt-image-c',
        'active-button',
        'position-open',
        'list-open'
      ],
    }),
  ],
}